/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import analizadorSintactico.LexerCup;
import analizadorSintactico.Sintax;
import java.io.IOException;
import java.io.StringReader;
import java.lang.System.Logger;
import java_cup.runtime.Symbol;
import analizadorSintactico.LexerCup;
import analizadorSintactico.LexerLexico;
import analizadorSintactico.Sintax;
import analizadorSintactico.Tokens;
import java.io.IOException;
import java.io.StringReader;
import java.util.logging.Level;

import java_cup.runtime.Symbol;
/**
 *
 * @author pavel
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciar = new javax.swing.JButton();
        textoMostrado = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtLexico = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        textoUsuario = new javax.swing.JTextArea();
        btnLexico = new javax.swing.JButton();
        lblSalida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIniciar.setText("Analizador Sintactico");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        txtLexico.setColumns(20);
        txtLexico.setRows(5);
        jScrollPane4.setViewportView(txtLexico);

        textoUsuario.setColumns(20);
        textoUsuario.setRows(5);
        textoUsuario.setText("[(\n{Por si al cabo lo cierto no barruntas}\n{Y dudando hasta el fin, no das en bola,}\n{Hacerle quiero a tu problema gola,}\n{Dándoles solución a tus preguntas.}\n)\n(\n{Ya miro ciertas frentes cejijuntas,}\n{Porque los sabios de capuz y estola,}\n{Temen que el sonetillo tenga cola,}\n{Rubicundo color, puntos y puntas.}\n)\n(\n{Que este bregar no es vida, ¿quién lo niega?}\n{Siempre de mingo la virtud, y ufana}\n{La iniquidad que triunfa en la refriega.}\n)\n(\n{¿Y al morir? Pues mejor Si no se gana,}\n{Y San Pedro a coristas nos agrega,}\n{Salimos de esta ¡noches! toledana.}\n)]\n");
        jScrollPane5.setViewportView(textoUsuario);

        btnLexico.setText("Analizador Lexico");
        btnLexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLexicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnIniciar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(textoMostrado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(btnLexico)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLexico)
                            .addComponent(btnIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)))
                .addComponent(textoMostrado)
                .addGap(204, 204, 204))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        
        //textoUsuario.
        String textoUs="";
        textoUs=textoUsuario.getText();   

        Sintax s=null;
        s = new Sintax(new LexerCup(new StringReader(textoUs)));
        
        try {
            s.parse();
            String aux1=("Texto correcto");
            lblSalida.setText(aux1);
        } catch (Exception e) {

            Symbol sym= s.getS();
            //  System.out.println(sym);
            String aux=("Error de sintaxis linea "+(sym.right + 1)+" columna "+(sym.left+1)+" Texto "+sym.value);
            lblSalida.setText(aux);

            // System.out.println("Error de sintaxis linea"+(sym.right + 1)+" columna "+(sym.left+1)+" Texto "+sym.value) ;
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnLexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLexicoActionPerformed
        // TODO add your handling code here:
        Lexico();
    }//GEN-LAST:event_btnLexicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
     public void Lexico(){
        try {
            
            String cadena = (String)textoUsuario.getText();
            LexerLexico lexer = new LexerLexico(new StringReader(cadena));  //la cadena
            String result ="";
            String resLexico = ""; 
            while (true) {                
                Tokens token =lexer.yylex();
                
                
                if (token == null) {
                    result +="FIN";
                    break;
                }
                switch (token) {

                    case ERROR:
                        result += lexer.lexema+"Es un simbolo desconocido";
                        break;
                    case Poema_i:
                        result += lexer.lexema+" -->Inicio de poema";
                        break;    
                    case Poema_f:
                        result += lexer.lexema+" -->Fin de poema";
                        break; 
                    case Verso_i:
                        result += lexer.lexema+" --> Inicio de verso";
                        break;    
                    case Verso_f:
                        result += lexer.lexema+" --> Fin de verso";
                        break; 
                    case Parrafo_i:
                        result += lexer.lexema+" --> Inicio de parrafo";
                        break; 
                    case Parrafo_f:
                        result += lexer.lexema+" --> Fin de parrafo";
                        break; 
                    case Exclamacion_i:
                        result += lexer.lexema+" --> Inicio exclamacion";
                        break; 
                    case Exclamacion_f:
                        result += lexer.lexema+" -->Fin exclamacion";
                        break; 
                    case Interrogacion_i:
                        result += lexer.lexema+" -->Inicio interrogacion";
                        break; 
                    case Interrogacion_f:
                        result += lexer.lexema+" -->Fin interrogaciona";
                        break; 
                    case Punto:
                        result += lexer.lexema+" --> Punto";
                        break; 
                    case Coma:
                        result += lexer.lexema+" --> Coma";
                        break; 
                    case Punto_coma:
                        result += lexer.lexema+" -->  Punto y coma";
                        break; 
                    case Cadena_texto:
                        result += lexer.lexema+" --> Cadena de texto";  
                        break; 
                    case Numero:
                        result += lexer.lexema+" --> Numero";
                        break; 
                    
                }
                resLexico = resLexico + result+ "\n";

                //System.out.println(result);
                result="";
            }
            txtLexico.setText(resLexico);
        } catch (Exception e) {
            System.out.println("error "+e);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnLexico;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblSalida;
    private javax.swing.JLabel textoMostrado;
    private javax.swing.JTextArea textoUsuario;
    private javax.swing.JTextArea txtLexico;
    // End of variables declaration//GEN-END:variables
}

