
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 22 21:22:46 ECT 2022
//----------------------------------------------------

package analizadorSintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Parrafo_i = 6;
  public static final int Numero = 16;
  public static final int Parrafo_f = 7;
  public static final int Exclamacion_i = 8;
  public static final int Poema_i = 2;
  public static final int ERROR = 17;
  public static final int Verso_i = 4;
  public static final int Exclamacion_f = 9;
  public static final int Poema_f = 3;
  public static final int Verso_f = 5;
  public static final int Coma = 13;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Punto = 12;
  public static final int Cadena_texto = 15;
  public static final int Interrogacion_i = 10;
  public static final int Punto_coma = 14;
  public static final int Interrogacion_f = 11;
}

